const data = {
  tasks: [
    {
      id: 1023,
      created: "1 day ago",
      name: "Mobile account settings view",
      priority: "Normal",
      status: "new",
      scope: "Mobile, App",
      comments: 10,
      attachemnts: 6,
      owner: "male-two.jpeg",
    },
    {
      id: 957,
      created: "5 days ago",
      name: "Dribbble Freebies - blog template",
      priority: "Normal",
      status: "new",
      scope: "Template, Dribbble, shot, Freebies",
      comments: 0,
      attachemnts: 1,
      owner: "female-two.jpg",
    },
    {
      id: 1021,
      created: "1 day ago",
      name: "Chatmail - redesign",
      priority: "High",
      status: "inprogress",
      scope: "Mobile, App",
      comments: 15,
      attachemnts: 9,
      owner: "female-two.jpg",
    },
    {
      id: 1011,
      created: "2 days ago",
      name: "Video Dashboard",
      priority: "Urgent",
      status: "inprogress",
      scope: "Web, Dashboard",
      comments: 0,
      attachemnts: 2,
      owner: "female-two.jpg",
    },
    {
      id: 946,
      created: "10 days ago",
      name: "Mystic Landing Page",
      priority: "Normal",
      status: "inprogress",
      scope: "Landing, Web, RWD",
      comments: 2,
      attachemnts: 1,
      owner: "femalte-threee.jpeg",
    },
    {
      id: 1022,
      created: "1 day ago",
      name: "Magazine Homepage",
      priority: "Urgent",
      status: "review",
      scope: "Web, Homepage, RWD",
      comments: 12,
      attachemnts: 2,
      owner: "femalte-threee.jpeg",
    },
    {
      id: 984,
      created: "3 days ago",
      name: "Web account setting view",
      priority: "Normal",
      status: "done",
      scope: "Web, App",
      comments: 10,
      attachemnts: 6,
      owner: "femalte-threee.jpeg",
    },
    {
      id: 1002,
      created: "2 days ago",
      name: "Mobile App - all preview jpg",
      priority: "Low",
      status: "done",
      scope: "Mobile, App",
      comments: 1,
      attachemnts: 24,
      owner: "female-one.jpeg",
    },
    {
      id: 976,
      created: "2 days ago",
      name: "Register form optimization",
      priority: "High",
      status: "done",
      scope: "Register, Form, Web",
      comments: 10,
      attachemnts: 6,
      owner: "female-one.jpeg",
    },
    {
      id: 1018,
      created: "2 days ago",
      name: "Assets for developers",
      priority: "Urgent",
      status: "done",
      scope: "Mobile, App",
      comments: 0,
      attachemnts: 0,
      owner: "male-two.jpeg",
    },
  ],
};

export default data;
